{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.knifffe",
    "module": "logging-starter-gradle",
    "version": "1.0.0-RC1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-gradle-1.0.0-RC1.jar",
          "url": "logging-starter-gradle-1.0.0-RC1.jar",
          "size": 9809,
          "sha512": "7344df9b809aee2b6004cbede3b4712b91086374467bfa0d61bc93a43be1270523abda50b1e665650734ce0538ec05f399a1d0ef95fbf6357ad76093d131f504",
          "sha256": "ec646f18c9a90aea9e19b2090699c07bca55d14d040dcd4fc3bfc4a49fb4889f",
          "sha1": "63d8952c65f5ea5f68da080e2fb5346e9a93a7f9",
          "md5": "f6bd3ba7f04ecc3579b877644e5ce5b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "logging-starter-gradle-1.0.0-RC1.jar",
          "url": "logging-starter-gradle-1.0.0-RC1.jar",
          "size": 9809,
          "sha512": "7344df9b809aee2b6004cbede3b4712b91086374467bfa0d61bc93a43be1270523abda50b1e665650734ce0538ec05f399a1d0ef95fbf6357ad76093d131f504",
          "sha256": "ec646f18c9a90aea9e19b2090699c07bca55d14d040dcd4fc3bfc4a49fb4889f",
          "sha1": "63d8952c65f5ea5f68da080e2fb5346e9a93a7f9",
          "md5": "f6bd3ba7f04ecc3579b877644e5ce5b1"
        }
      ]
    }
  ]
}
